### ISSUE TITLE
i need help get error

### ISSUE THREAD

**Issue by addepade08** [datagutten/mulle.js#19]
I get the error type that there was no text file in the 08 folder but I added the txt files but now I get this

I get that it can't find score
![image](https://user-images.githubusercontent.com/69600142/219430838-2f69e72a-6e90-4f56-b11a-0023bd19e6b3.png)

**Comment by addepade08** [comment]
![image](https://user-images.githubusercontent.com/69600142/219880193-4d48c372-1f45-4fd8-8a4f-5cad9ce835ec.png)
now I have solved it and this is the only thing I get now

**Comment by datagutten** [comment]
I think this is fixed now. Imagemagick started complaining of invalid colormap and would produce files. I have changed the conversion to use pillow instead.
